# Generated by Django 4.1.4 on 2022-12-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_add',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
