# Generated by Django 4.1.4 on 2022-12-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_name_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
