# Generated by Django 4.1.4 on 2022-12-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_name_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
